# Generated by Django 3.0.6 on 2020-05-21 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0004_remove_profile_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='brach',
            new_name='branch',
        ),
    ]
