# Generated by Django 3.0.6 on 2020-05-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0009_auto_20200522_2332'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='my_img',
            field=models.ImageField(null=True, upload_to='images\\'),
        ),
    ]
