# Generated by Django 3.0.6 on 2020-05-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0010_profile_my_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='my_img',
            field=models.FileField(null=True, upload_to='docs\\'),
        ),
    ]
