# Generated by Django 3.0.6 on 2020-05-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0011_auto_20200523_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='myresume',
            field=models.FileField(null=True, upload_to='docs\\'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='my_img',
            field=models.ImageField(null=True, upload_to='images\\'),
        ),
    ]
